title: Nihit Jain's GitHub
author: Nihit Jain 
email: nihitjain11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Will be writing an awesome description for my new site here. I can edit this
  line in _config.yml. It will appear in my document head meta (for
  Google search results) and in my feed.xml site description.

# social links
twitter_username: nihitjain11
github_username:  nihitjain11

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
